apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: zero2prod
build:
  local:
    push: true
    useBuildkit: true  
  tagPolicy:
      envTemplate:
        template: "{{.IMAGE_TAG}}"
  artifacts:
  - image: zero2prod
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: kind-zero2prod
  kubectl:
    manifests:
      - k8s/base/namespace.yaml
      - k8s/base/postgres.yaml
      - k8s/base/core.yaml
      # - k8s/base/migrations.yaml TODO: automate migration using 
  kustomize:
    paths:
      - k8s/base

portForward:
  - resourceType: service
    namespace: zero2prod
    resourceName: zero2prod-svc
    port: 8000
    localPort: 8000
  - resourceType: service
    namespace: zero2prod
    resourceName: postgres-svc
    port: 5432
    localPort: 5432