apiVersion: batch/v1
kind: Job
metadata:
  name: sqlx-migration-job
spec:
  template:
    spec:
      containers:
      - name: migration
        image: rust:slim-bullseye
        command: |
          cargo install sqlx-cli --no-default-features --features native-tls,postgres
      restartPolicy: Never
  backoffLimit: 1