apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: zero2prod
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DATABASE_NAME: newsletter
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: zero2prod
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          # env:
          #   - name: POSTGRES_DB
          #     value: newsletter
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: zero2prod
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432